"""Section indexes: docs/wiki/<type>/index.md and docs/wiki/index.md.

Both are fully generated from the pages on disk (so a partial build still
leaves every index right); do not edit them by hand.
"""
from . import common
from .common import OUT, cell, parse_front_matter

ORDER = ["items", "skills", "buffs", "monsters", "npcs", "quests", "shops", "fields",
         "zones", "dungeons", "teleports", "sets", "heroes", "masteries", "achievements",
         "classes", "objects"]


def scan(type_):
    rows = []
    for f in (OUT / type_).glob("*.md"):
        if f.name == "index.md":
            continue
        fm, _ = parse_front_matter(f.read_text(encoding="utf-8"))
        try:
            id_ = int(fm.get("id"))
        except (TypeError, ValueError):
            continue
        missing = fm.get("missing") if isinstance(fm.get("missing"), list) else []
        rows.append((id_, f.stem, fm.get("title") or f.stem, fm.get("status") or "stub", missing))
    return sorted(rows)


def plural(ctx, type_):
    mod = ctx.module(type_)
    return getattr(mod, "PLURAL", None) or ctx.label(type_) + "s"


def write_if_changed(path, text, ctx):
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return
    if not ctx.dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


def write_indexes(ctx):
    if not OUT.is_dir():
        return
    types = [d.name for d in OUT.iterdir() if d.is_dir() and d.name != "assets"]
    types.sort(key=lambda t: (ORDER.index(t) if t in ORDER else 99, t))
    summary = []
    for t in types:
        rows = scan(t)
        if not rows:
            continue
        counts = {"complete": 0, "partial": 0, "stub": 0}
        table = []
        for id_, stem, title, status, missing in rows:
            counts[status] = counts.get(status, 0) + 1
            img = "![](wiki/assets/%s/%d.png)" % (t, id_) if (common.ASSETS / t / ("%d.png" % id_)).exists() else ""
            table.append((img, id_, "[[wiki/%s/%s\\|%s]]" % (t, stem, common.link_text(str(title))),
                          status, len(missing)))
        mod = ctx.module(t)
        desc = getattr(mod, "DESCRIPTION", "") if mod else ""
        name = plural(ctx, t)
        text = ['---', 'title: "%s"' % name, '---', '',
                '<!-- generated by wiki/gamewiki (index.py); do not edit -->', '',
                '# %s' % name, '']
        if desc:
            text += [desc.strip(), '']
        text += ['%d pages: %d complete, %d partial, %d stub. Back to the [[wiki/index|game wiki]].' % (
            len(rows), counts["complete"], counts["partial"], counts["stub"]), '',
            "| | id | name | status | missing |", "|---|---|---|---|---|"]
        text += ["| %s | %d | %s | %s | %d |" % r for r in table]
        text += ['', '*%s*' % common.CREDIT, '']
        write_if_changed(OUT / t / "index.md", "\n".join(text), ctx)
        summary.append((t, name, len(rows), counts))
    text = ['---', 'title: "Game wiki"', '---', '',
            '<!-- generated by wiki/gamewiki (index.py); do not edit -->', '',
            '# Game wiki', '',
            'One page per thing in the game: every item, skill, buff, monster, NPC, quest, shop, '
            'map and dungeon. The pages are the **source of truth the server is built from**: '
            'the structured part at the top of each page (front matter) is what the server loads.',
            '',
            'Every page starts from the original client\'s own data (names, stats, prices, '
            'quest texts, icons) and is then filled in by hand. Values the client never had '
            '(monster HP, drop rates, damage formulas, where NPCs stand) are what is still missing.',
            '',
            '| section | pages | complete | partial | stub |', '|---|---|---|---|---|']
    tot = [0, 0, 0, 0]
    for t, name, n, c in summary:
        text.append("| [[wiki/%s/index\\|%s]] | %d | %d | %d | %d |" % (t, name, n, c["complete"], c["partial"], c["stub"]))
        for i, v in enumerate((n, c["complete"], c["partial"], c["stub"])):
            tot[i] += v
    text.append("| **total** | %d | %d | %d | %d |" % tuple(tot))
    text += ['',
             '**complete** = every field the server needs has a value (from the client data or added '
             'by hand); **partial** = fields are still missing but someone has added to the page; '
             '**stub** = fields are missing and the page holds only what the client data gives.',
             '',
             '## How to contribute',
             '',
             '1. **Pick a stub.** Open a section index and choose a page marked *stub* or *partial*. '
             'Its `missing:` list (front matter, top of the page) names the fields still undefined.',
             '2. **Fill the fields.** Add each missing field to the front matter with the same name, '
             'using ids for references (an item id, a unit id, a field id). Write what you know in '
             '*Notes*, *Behaviour* and *Open questions*.',
             '3. **Cite sources.** Add a line to `sources:` for every fact (a guide, a video with '
             'timestamp, a captured packet, a client table and column) and say how sure you are; see '
             '[[wiki-style|How to write wiki pages]].',
             '4. **Leave the generated part alone.** The block between `generated:start` and '
             '`generated:end` and the client-derived fields are rewritten by '
             '`python3 -m wiki.gamewiki build`. If a client value is wrong, change it in the front '
             'matter: the generator notices the edit, lists the field under `manual:` and never '
             'overwrites it.',
             '',
             'Related: [[gameplay/README|Gameplay]] (what the game was, from guides and video), '
             '[[spec/data-tables|Data tables]] (what each client table holds).',
             '',
             '*%s*' % common.CREDIT, '']
    write_if_changed(OUT / "index.md", "\n".join(text), ctx)
