"""Section indexes: docs/wiki/<type>/index.md and docs/wiki/index.md.

Both are fully generated from the pages on disk (so a partial build still
leaves every index right); do not edit them by hand.
"""
from . import common
from .common import OUT, cell, parse_front_matter

ORDER = ["items", "skills", "buffs", "monsters", "npcs", "quests", "shops", "fields",
         "zones", "dungeons", "teleports", "sets", "classes", "heroes", "costumes", "masteries",
         "achievements", "fame-ranks", "objects"]


def scan(type_):
    rows = []
    for f in (OUT / type_).glob("*.md"):
        if f.name == "index.md":
            continue
        fm, _ = parse_front_matter(f.read_text(encoding="utf-8"))
        try:
            id_ = int(fm.get("id"))
        except (TypeError, ValueError):
            continue
        missing = fm.get("missing") if isinstance(fm.get("missing"), list) else []
        rows.append((id_, f.stem, fm.get("title") or f.stem, fm.get("status") or "stub", missing))
    return sorted(rows)


def plural(ctx, type_):
    mod = ctx.module(type_)
    return getattr(mod, "PLURAL", None) or ctx.label(type_) + "s"


def write_if_changed(path, text, ctx):
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return
    if not ctx.dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


def write_indexes(ctx):
    if not OUT.is_dir():
        return
    types = [d.name for d in OUT.iterdir() if d.is_dir() and d.name != "assets"]
    types.sort(key=lambda t: (ORDER.index(t) if t in ORDER else 99, t))
    summary = []
    for t in types:
        rows = scan(t)
        if not rows:
            continue
        counts = {"complete": 0, "partial": 0, "stub": 0}
        table = []
        for id_, stem, title, status, missing in rows:
            counts[status] = counts.get(status, 0) + 1
            img = "![](wiki/assets/%s/%d.png)" % (t, id_) if (common.ASSETS / t / ("%d.png" % id_)).exists() else ""
            table.append((img, id_, "[[wiki/%s/%s\\|%s]]" % (t, stem, common.link_text(str(title))),
                          status, len(missing)))
        mod = ctx.module(t)
        desc = getattr(mod, "DESCRIPTION", "") if mod else ""
        name = plural(ctx, t)
        text = ['---', 'title: "%s"' % name, '---', '',
                '<!-- generated by wiki/gamewiki (index.py); do not edit -->', '',
                '# %s' % name, '']
        if desc:
            text += [desc.strip(), '']
        if t == "items":
            text += ['**Categories:** ' + category_links(), '']
        text += ['%d pages: %d complete, %d partial, %d stub. Back to the [[wiki/index|game wiki]].' % (
            len(rows), counts["complete"], counts["partial"], counts["stub"]), '',
            "| | id | name | status | missing |", "|---|---|---|---|---|"]
        text += ["| %s | %d | %s | %s | %d |" % r for r in table]
        text += ['', '*%s*' % common.CREDIT, '']
        write_if_changed(OUT / t / "index.md", "\n".join(text), ctx)
        summary.append((t, name, len(rows), counts))
    write_item_categories(ctx)
    text = ['---', 'title: "Game wiki"', '---', '',
            '<!-- generated by wiki/gamewiki (index.py); do not edit -->', '',
            '# Game wiki', '',
            'One page per thing in the game: every item, skill, buff, monster, NPC, quest, shop, '
            'map and dungeon, plus the classes, hero forms, costumes, masteries, achievements and '
            'fame ranks. The pages are the **source of truth the server is built from**: '
            'the structured part at the top of each page (front matter) is what the server loads.',
            '',
            'Every page starts from the original client\'s own data (names, stats, prices, '
            'quest texts, icons) and is then filled in by hand. Values the client never had '
            '(monster HP, drop rates, damage formulas, where NPCs stand) are what is still missing.',
            '',
            '| section | pages | complete | partial | stub |', '|---|---|---|---|---|']
    tot = [0, 0, 0, 0]
    for t, name, n, c in summary:
        text.append("| [[wiki/%s/index\\|%s]] | %d | %d | %d | %d |" % (t, name, n, c["complete"], c["partial"], c["stub"]))
        for i, v in enumerate((n, c["complete"], c["partial"], c["stub"])):
            tot[i] += v
    text.append("| **total** | %d | %d | %d | %d |" % tuple(tot))
    text += ['', '**Item categories:** ' + category_links(), '',
             '**complete** = every field the server needs has a value (from the client data or added '
             'by hand); **partial** = fields are still missing but someone has added to the page; '
             '**stub** = fields are missing and the page holds only what the client data gives.',
             '',
             '## How to contribute',
             '',
             '1. **Pick a stub.** Open a section index and choose a page marked *stub* or *partial*. '
             'Its `missing:` list (front matter, top of the page) names the fields still undefined.',
             '2. **Fill the fields.** Add each missing field to the front matter with the same name, '
             'using ids for references (an item id, a unit id, a field id). Write what you know in '
             '*Notes*, *Behaviour* and *Open questions*.',
             '3. **Cite sources.** Add a line to `sources:` for every fact (a guide, a video with '
             'timestamp, a captured packet, a client table and column) and say how sure you are; see '
             '[[wiki-style|How to write wiki pages]].',
             '4. **Leave the generated part alone.** The block between `generated:start` and '
             '`generated:end` and the client-derived fields are rewritten by '
             '`python3 -m wiki.gamewiki build`. If a client value is wrong, change it in the front '
             'matter: the generator notices the edit, lists the field under `manual:` and never '
             'overwrites it.',
             '',
             'Related: [[gameplay/README|Gameplay]] (what the game was, from guides and video), '
             '[[spec/data-tables|Data tables]] (what each client table holds).',
             '',
             '*%s*' % common.CREDIT, '']
    write_if_changed(OUT / "index.md", "\n".join(text), ctx)


# ------------------------------------------------------------ item categories

def category_links():
    from .items import CATEGORIES
    return " · ".join("[[wiki/items/%s\\|%s]]" % (slug, title) for slug, title, _k, _d in CATEGORIES)


def _stats_text(fm):
    out = []
    for st in fm.get("stats") or []:
        if isinstance(st, dict) and st.get("scale") != "tier":
            v = st.get("value")
            out.append("%s %s" % (st.get("stat"), "%+d" % v if isinstance(v, int) else v))
    return ", ".join(out[:5]) + (" …" if len(out) > 5 else "")


def _grade(fm):
    """Armour / accessory group: tier (T1-T3) belongs to each copy, not to the
    Item_Base row, so rows are grouped by what the row does say."""
    if fm.get("set"):
        return 3, "Set pieces (boss and fame sets)"
    if fm.get("rarity"):
        return 2, "Superior (rarity 1)"
    price = fm.get("price") if isinstance(fm.get("price"), dict) else {}
    if not price.get("buy"):
        return 0, "Starter and special"
    return 1, "Basic"


def write_item_categories(ctx):
    """docs/wiki/items/<slug>.md for every items.CATEGORIES entry, from the
    item pages' front matter (kind, classes, stats, price, rarity, set)."""
    from . import items
    folder = OUT / "items"
    if not folder.is_dir():
        return
    pages = {}
    for f in folder.glob("*.md"):
        if f.name == "index.md":
            continue
        fm, _ = parse_front_matter(f.read_text(encoding="utf-8"))
        try:
            pages[int(fm.get("id"))] = (f.stem, fm)
        except (TypeError, ValueError):
            continue
    by_cat = {}
    for id_, (stem, fm) in sorted(pages.items()):
        by_cat.setdefault(items.category(fm), []).append((id_, stem, fm))
    grouped = {"armor-helmet", "armor-body", "armor-gloves", "armor-shoes", "accessories"}
    for slug, title, kinds, blurb in items.CATEGORIES:
        rows = by_cat.get(slug, [])
        weapons = slug.startswith("weapons-")
        text = ['---', 'title: "%s"' % title, '---', '',
                '<!-- generated by wiki/gamewiki (index.py); do not edit -->', '',
                '# %s' % title, '', blurb, '']
        if weapons:
            cname = title.split()[0]
            text += ['Class page: [[wiki/classes/%s\\|%s]]. The weapon decides the skills: Q/W/E/R are '
                     'the weapon\'s four normal skills (`WeaponBase`).' % (
                         ctx.path("classes", items.CLASS_UNITS[cname]).split("/", 2)[2], cname), '']
        if slug in grouped:
            text += ['Tier (T1–T3) is a property of each copy, not of the item row: the client multiplies '
                     'the first three stat slots by *tier × 15 + reinforce level* (see any item page). '
                     'Rows are grouped by grade instead.', '']
        if slug == "costume-items":
            text += ['Grouped by set: [[wiki/costumes/index\\|Costumes]].', '']
        if slug == "hero-items":
            text += ['Hero forms: [[wiki/heroes/index\\|Heroes]].', '']
        text += ['%d items. Back to [[wiki/items/index\\|Items]]; other categories: %s.' % (
            len(rows), " · ".join("[[wiki/items/%s\\|%s]]" % (c[0], c[1]) for c in items.CATEGORIES if c[0] != slug)), '']
        groups = {}
        for id_, stem, fm in rows:
            key = _grade(fm) if slug in grouped else (0, "")
            groups.setdefault(key, []).append((id_, stem, fm))
        for (_n, gname), grows in sorted(groups.items()):
            if gname:
                text += ['## %s' % gname, '']
            head = ["", "id", "name", "kind"]
            head += ["skills (Q/W/E/R)"] if weapons else ["classes"]
            head += ["stats", "price", "status"]
            text += ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
            for id_, stem, fm in grows:
                img = "![](wiki/assets/items/%d.png)" % id_ if (common.ASSETS / "items" / ("%d.png" % id_)).exists() else ""
                link = "[[wiki/items/%s\\|%s]]" % (stem, common.link_text(str(fm.get("title") or stem)))
                if weapons:
                    sk = [x for x in fm.get("skills") or [] if isinstance(x, int)][:4]
                    extra = ", ".join(ctx.link("skills", x).replace("|", "\\|") for x in sk)
                else:
                    cl = fm.get("classes")
                    extra = "all" if cl == "all" else ", ".join(cl or []) or "–"
                price = fm.get("price") if isinstance(fm.get("price"), dict) else {}
                pr = "%s %s" % (common.fmt_num(price.get("buy", 0)), price.get("currency_name", "")) if price.get("buy") else "–"
                text.append("| %s | %d | %s | %s | %s | %s | %s | %s |" % (
                    img, id_, link, cell(fm.get("kind_name") or fm.get("kind")), extra, cell(_stats_text(fm)),
                    cell(pr), fm.get("status") or "stub"))
            text.append("")
        text += ['*%s*' % common.CREDIT, '']
        body = common.unlink_missing(ctx, "\n".join(text))
        write_if_changed(folder / ("%s.md" % slug), body, ctx)
